// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2016.4
// Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#ifndef _singleGUV_HH_
#define _singleGUV_HH_

#include "systemc.h"
#include "AESL_pkg.h"

#include "DCT_8x8_2D_fptrunbkb.h"
#include "DCT_8x8_2D_fpext_cud.h"
#include "DCT_8x8_2D_dadd_6dEe.h"
#include "DCT_8x8_2D_dmul_6eOg.h"

namespace ap_rtl {

struct singleGUV : public sc_module {
    // Port declarations 16
    sc_in_clk ap_clk;
    sc_in< sc_logic > ap_rst;
    sc_in< sc_logic > ap_start;
    sc_out< sc_logic > ap_done;
    sc_out< sc_logic > ap_idle;
    sc_out< sc_logic > ap_ready;
    sc_out< sc_lv<6> > subimg_address0;
    sc_out< sc_logic > subimg_ce0;
    sc_in< sc_lv<32> > subimg_q0;
    sc_in< sc_lv<4> > u;
    sc_in< sc_lv<4> > v;
    sc_in< sc_lv<32> > inv;
    sc_out< sc_lv<6> > cosMat_address0;
    sc_out< sc_logic > cosMat_ce0;
    sc_in< sc_lv<32> > cosMat_q0;
    sc_out< sc_lv<32> > ap_return;
    sc_signal< sc_logic > ap_var_for_const0;


    // Module declarations
    singleGUV(sc_module_name name);
    SC_HAS_PROCESS(singleGUV);

    ~singleGUV();

    sc_trace_file* mVcdFile;

    DCT_8x8_2D_fptrunbkb<1,1,64,32>* DCT_8x8_2D_fptrunbkb_U0;
    DCT_8x8_2D_fpext_cud<1,1,32,64>* DCT_8x8_2D_fpext_cud_U1;
    DCT_8x8_2D_dadd_6dEe<1,4,64,64,64>* DCT_8x8_2D_dadd_6dEe_U2;
    DCT_8x8_2D_dmul_6eOg<1,4,64,64,64>* DCT_8x8_2D_dmul_6eOg_U3;
    sc_signal< sc_lv<29> > ap_CS_fsm;
    sc_signal< sc_lv<1> > ap_CS_fsm_state1;
    sc_signal< sc_lv<64> > grp_fu_135_p1;
    sc_signal< sc_lv<64> > reg_152;
    sc_signal< sc_lv<1> > ap_CS_fsm_state7;
    sc_signal< sc_lv<1> > tmp_reg_404;
    sc_signal< sc_lv<64> > reg_157;
    sc_signal< sc_lv<1> > ap_CS_fsm_state9;
    sc_signal< sc_lv<1> > ap_CS_fsm_state17;
    sc_signal< sc_lv<1> > ap_CS_fsm_state24;
    sc_signal< sc_lv<64> > grp_fu_144_p2;
    sc_signal< sc_lv<64> > reg_163;
    sc_signal< sc_lv<1> > ap_CS_fsm_state12;
    sc_signal< sc_lv<1> > ap_CS_fsm_state16;
    sc_signal< sc_lv<1> > ap_CS_fsm_state20;
    sc_signal< sc_lv<64> > reg_168;
    sc_signal< sc_lv<1> > ap_CS_fsm_state13;
    sc_signal< sc_lv<1> > ap_CS_fsm_state21;
    sc_signal< sc_lv<1> > tmp_fu_173_p2;
    sc_signal< sc_lv<1> > tmp_i_fu_179_p2;
    sc_signal< sc_lv<1> > tmp_i_reg_409;
    sc_signal< sc_lv<1> > tmp_i1_fu_185_p2;
    sc_signal< sc_lv<1> > tmp_i1_reg_414;
    sc_signal< sc_lv<64> > tmp_4_fu_196_p3;
    sc_signal< sc_lv<1> > ap_CS_fsm_state2;
    sc_signal< sc_lv<64> > tmp_6_fu_204_p3;
    sc_signal< sc_lv<8> > v_cast2_cast_fu_212_p1;
    sc_signal< sc_lv<8> > v_cast2_cast_reg_429;
    sc_signal< sc_lv<1> > ap_CS_fsm_state5;
    sc_signal< sc_lv<8> > tmp_19_cast_fu_222_p1;
    sc_signal< sc_lv<8> > tmp_19_cast_reg_434;
    sc_signal< sc_lv<8> > u_cast1_cast_fu_226_p1;
    sc_signal< sc_lv<8> > u_cast1_cast_reg_439;
    sc_signal< sc_lv<8> > tmp_21_cast_fu_236_p1;
    sc_signal< sc_lv<8> > tmp_21_cast_reg_444;
    sc_signal< sc_lv<64> > tmp_7_reg_449;
    sc_signal< sc_lv<8> > tmp_23_cast_fu_252_p1;
    sc_signal< sc_lv<8> > tmp_23_cast_reg_454;
    sc_signal< sc_lv<1> > ap_CS_fsm_state6;
    sc_signal< sc_lv<4> > x_fu_282_p2;
    sc_signal< sc_lv<4> > x_reg_472;
    sc_signal< sc_lv<1> > tmp_i2_fu_288_p2;
    sc_signal< sc_lv<1> > tmp_i2_reg_477;
    sc_signal< sc_lv<1> > exitcond1_fu_276_p2;
    sc_signal< sc_lv<64> > tmp_2_fu_294_p3;
    sc_signal< sc_lv<64> > tmp_2_reg_482;
    sc_signal< sc_lv<1> > ap_CS_fsm_state8;
    sc_signal< sc_lv<6> > cosMat_addr_2_reg_492;
    sc_signal< sc_lv<6> > cosMat_addr_3_reg_497;
    sc_signal< sc_lv<4> > y_fu_353_p2;
    sc_signal< sc_lv<4> > y_reg_505;
    sc_signal< sc_lv<1> > tmp_i3_fu_359_p2;
    sc_signal< sc_lv<1> > tmp_i3_reg_510;
    sc_signal< sc_lv<1> > exitcond_fu_347_p2;
    sc_signal< sc_lv<64> > tmp_12_fu_365_p3;
    sc_signal< sc_lv<64> > tmp_16_reg_520;
    sc_signal< sc_lv<64> > G_2_in_v_fu_373_p3;
    sc_signal< sc_lv<64> > G_2_in_v_reg_525;
    sc_signal< sc_lv<64> > grp_fu_140_p2;
    sc_signal< sc_lv<64> > G_2_in_reg_530;
    sc_signal< sc_lv<1> > ap_CS_fsm_state28;
    sc_signal< sc_lv<4> > x_assign_reg_110;
    sc_signal< sc_lv<4> > x_assign_1_reg_121;
    sc_signal< sc_lv<1> > ap_CS_fsm_state29;
    sc_signal< sc_lv<32> > tmp_24_cast_fu_261_p1;
    sc_signal< sc_lv<32> > tmp_25_cast_fu_271_p1;
    sc_signal< sc_lv<32> > tmp_26_cast_fu_310_p1;
    sc_signal< sc_lv<32> > tmp_27_cast_fu_320_p1;
    sc_signal< sc_lv<32> > tmp_30_cast_fu_342_p1;
    sc_signal< sc_lv<32> > G_fu_42;
    sc_signal< sc_lv<32> > G_1_fu_132_p1;
    sc_signal< sc_lv<1> > ap_CS_fsm_state19;
    sc_signal< sc_lv<32> > grp_fu_135_p0;
    sc_signal< sc_lv<1> > ap_CS_fsm_state25;
    sc_signal< sc_lv<64> > grp_fu_144_p0;
    sc_signal< sc_lv<64> > grp_fu_144_p1;
    sc_signal< sc_lv<1> > ap_CS_fsm_state10;
    sc_signal< sc_lv<1> > ap_CS_fsm_state14;
    sc_signal< sc_lv<1> > ap_CS_fsm_state18;
    sc_signal< sc_lv<7> > tmp_18_fu_215_p3;
    sc_signal< sc_lv<7> > tmp_19_fu_229_p3;
    sc_signal< sc_lv<7> > tmp_20_fu_244_p3;
    sc_signal< sc_lv<8> > x_assign_cast2_cast_fu_240_p1;
    sc_signal< sc_lv<8> > tmp_21_fu_256_p2;
    sc_signal< sc_lv<8> > tmp_22_fu_266_p2;
    sc_signal< sc_lv<8> > x_assign_1_cast1_cas_fu_301_p1;
    sc_signal< sc_lv<8> > tmp_23_fu_305_p2;
    sc_signal< sc_lv<8> > tmp_24_fu_315_p2;
    sc_signal< sc_lv<7> > tmp_25_fu_325_p3;
    sc_signal< sc_lv<8> > tmp_29_cast_fu_333_p1;
    sc_signal< sc_lv<8> > tmp_26_fu_337_p2;
    sc_signal< sc_lv<29> > ap_NS_fsm;
    static const sc_logic ap_const_logic_1;
    static const sc_logic ap_const_logic_0;
    static const sc_lv<29> ap_ST_fsm_state1;
    static const sc_lv<29> ap_ST_fsm_state2;
    static const sc_lv<29> ap_ST_fsm_state3;
    static const sc_lv<29> ap_ST_fsm_state4;
    static const sc_lv<29> ap_ST_fsm_state5;
    static const sc_lv<29> ap_ST_fsm_state6;
    static const sc_lv<29> ap_ST_fsm_state7;
    static const sc_lv<29> ap_ST_fsm_state8;
    static const sc_lv<29> ap_ST_fsm_state9;
    static const sc_lv<29> ap_ST_fsm_state10;
    static const sc_lv<29> ap_ST_fsm_state11;
    static const sc_lv<29> ap_ST_fsm_state12;
    static const sc_lv<29> ap_ST_fsm_state13;
    static const sc_lv<29> ap_ST_fsm_state14;
    static const sc_lv<29> ap_ST_fsm_state15;
    static const sc_lv<29> ap_ST_fsm_state16;
    static const sc_lv<29> ap_ST_fsm_state17;
    static const sc_lv<29> ap_ST_fsm_state18;
    static const sc_lv<29> ap_ST_fsm_state19;
    static const sc_lv<29> ap_ST_fsm_state20;
    static const sc_lv<29> ap_ST_fsm_state21;
    static const sc_lv<29> ap_ST_fsm_state22;
    static const sc_lv<29> ap_ST_fsm_state23;
    static const sc_lv<29> ap_ST_fsm_state24;
    static const sc_lv<29> ap_ST_fsm_state25;
    static const sc_lv<29> ap_ST_fsm_state26;
    static const sc_lv<29> ap_ST_fsm_state27;
    static const sc_lv<29> ap_ST_fsm_state28;
    static const sc_lv<29> ap_ST_fsm_state29;
    static const sc_lv<32> ap_const_lv32_0;
    static const sc_lv<1> ap_const_lv1_1;
    static const sc_lv<32> ap_const_lv32_6;
    static const sc_lv<1> ap_const_lv1_0;
    static const sc_lv<32> ap_const_lv32_8;
    static const sc_lv<32> ap_const_lv32_10;
    static const sc_lv<32> ap_const_lv32_17;
    static const sc_lv<32> ap_const_lv32_B;
    static const sc_lv<32> ap_const_lv32_F;
    static const sc_lv<32> ap_const_lv32_13;
    static const sc_lv<32> ap_const_lv32_C;
    static const sc_lv<32> ap_const_lv32_14;
    static const sc_lv<32> ap_const_lv32_1;
    static const sc_lv<32> ap_const_lv32_4;
    static const sc_lv<32> ap_const_lv32_5;
    static const sc_lv<32> ap_const_lv32_7;
    static const sc_lv<32> ap_const_lv32_1B;
    static const sc_lv<4> ap_const_lv4_0;
    static const sc_lv<32> ap_const_lv32_1C;
    static const sc_lv<32> ap_const_lv32_12;
    static const sc_lv<32> ap_const_lv32_18;
    static const sc_lv<32> ap_const_lv32_9;
    static const sc_lv<32> ap_const_lv32_D;
    static const sc_lv<32> ap_const_lv32_11;
    static const sc_lv<64> ap_const_lv64_3FC6A09E60000000;
    static const sc_lv<64> ap_const_lv64_3FD0000000000000;
    static const sc_lv<64> ap_const_lv64_3FE6A09E60000000;
    static const sc_lv<64> ap_const_lv64_3FF0000000000000;
    static const sc_lv<3> ap_const_lv3_0;
    static const sc_lv<4> ap_const_lv4_8;
    static const sc_lv<4> ap_const_lv4_1;
    // Thread declarations
    void thread_ap_var_for_const0();
    void thread_ap_clk_no_reset_();
    void thread_G_2_in_v_fu_373_p3();
    void thread_ap_CS_fsm_state1();
    void thread_ap_CS_fsm_state10();
    void thread_ap_CS_fsm_state12();
    void thread_ap_CS_fsm_state13();
    void thread_ap_CS_fsm_state14();
    void thread_ap_CS_fsm_state16();
    void thread_ap_CS_fsm_state17();
    void thread_ap_CS_fsm_state18();
    void thread_ap_CS_fsm_state19();
    void thread_ap_CS_fsm_state2();
    void thread_ap_CS_fsm_state20();
    void thread_ap_CS_fsm_state21();
    void thread_ap_CS_fsm_state24();
    void thread_ap_CS_fsm_state25();
    void thread_ap_CS_fsm_state28();
    void thread_ap_CS_fsm_state29();
    void thread_ap_CS_fsm_state5();
    void thread_ap_CS_fsm_state6();
    void thread_ap_CS_fsm_state7();
    void thread_ap_CS_fsm_state8();
    void thread_ap_CS_fsm_state9();
    void thread_ap_done();
    void thread_ap_idle();
    void thread_ap_ready();
    void thread_ap_return();
    void thread_cosMat_address0();
    void thread_cosMat_ce0();
    void thread_exitcond1_fu_276_p2();
    void thread_exitcond_fu_347_p2();
    void thread_grp_fu_135_p0();
    void thread_grp_fu_144_p0();
    void thread_grp_fu_144_p1();
    void thread_subimg_address0();
    void thread_subimg_ce0();
    void thread_tmp_12_fu_365_p3();
    void thread_tmp_18_fu_215_p3();
    void thread_tmp_19_cast_fu_222_p1();
    void thread_tmp_19_fu_229_p3();
    void thread_tmp_20_fu_244_p3();
    void thread_tmp_21_cast_fu_236_p1();
    void thread_tmp_21_fu_256_p2();
    void thread_tmp_22_fu_266_p2();
    void thread_tmp_23_cast_fu_252_p1();
    void thread_tmp_23_fu_305_p2();
    void thread_tmp_24_cast_fu_261_p1();
    void thread_tmp_24_fu_315_p2();
    void thread_tmp_25_cast_fu_271_p1();
    void thread_tmp_25_fu_325_p3();
    void thread_tmp_26_cast_fu_310_p1();
    void thread_tmp_26_fu_337_p2();
    void thread_tmp_27_cast_fu_320_p1();
    void thread_tmp_29_cast_fu_333_p1();
    void thread_tmp_2_fu_294_p3();
    void thread_tmp_30_cast_fu_342_p1();
    void thread_tmp_4_fu_196_p3();
    void thread_tmp_6_fu_204_p3();
    void thread_tmp_fu_173_p2();
    void thread_tmp_i1_fu_185_p2();
    void thread_tmp_i2_fu_288_p2();
    void thread_tmp_i3_fu_359_p2();
    void thread_tmp_i_fu_179_p2();
    void thread_u_cast1_cast_fu_226_p1();
    void thread_v_cast2_cast_fu_212_p1();
    void thread_x_assign_1_cast1_cas_fu_301_p1();
    void thread_x_assign_cast2_cast_fu_240_p1();
    void thread_x_fu_282_p2();
    void thread_y_fu_353_p2();
    void thread_ap_NS_fsm();
};

}

using namespace ap_rtl;

#endif
